bash run_scenario.bash General 0 &&
bash run_scenario.bash General 1 &&
bash run_scenario.bash General 2 &&
bash run_scenario.bash General 3 &&
bash run_scenario.bash General 4 &&
bash run_scenario.bash General 5 &&
bash run_scenario.bash General 6 &&
bash run_scenario.bash General 7 &&
bash run_scenario.bash General 8 &&
bash run_scenario.bash General 9 &&
bash run_scenario.bash General 10 &&
bash run_scenario.bash General 11 &&
bash run_scenario.bash General 12 &&
bash run_scenario.bash General 13 &&
bash run_scenario.bash General 14 &&
bash run_scenario.bash General 15 &&
bash run_scenario.bash General 16 &&
bash run_scenario.bash General 17 &&
bash run_scenario.bash General 18 &&
bash run_scenario.bash General 19 &&
bash run_scenario.bash General 20 &&
bash run_scenario.bash General 21 &&
bash run_scenario.bash General 22 &&
bash run_scenario.bash General 23 &&
bash run_scenario.bash General 24 &&
bash run_scenario.bash General 25 &&
bash run_scenario.bash General 26 &&
bash run_scenario.bash General 27 &&
bash run_scenario.bash General 28 &&
bash run_scenario.bash General 29